spring:
  application:
    name: astro-kundli
  datasource:
    url: jdbc:postgresql://postgres:5432/mydatabase
    username: myuser
    password: secret
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      jdbc:
        lob:
          non_contextual_creation: true



  # Logging settings
  logging:
    level:
      org.springframework: INFO
      org.hibernate.SQL: DEBUG # Logs all SQL queries (useful for debugging, but disable in production)

server:
  port: 8080 # Default port, change as needed

